name: my_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 0.18.0
  flutter_session: any
  auto_size_text: any
  getwidget: any
  fluttericon: any
  fluttertoast: any
  provider: any
  flutter_secure_storage: ^3.3.3
  folding_cell: any
  flutter_toggle_tab: ^0.0.2
  flutter_qr_bar_scanner: ^1.0.2
  url_launcher: any
  mailto: any
  workmanager: ^0.2.2
  flutter_local_notifications: ^1.4.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/svg/just_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/svg/
    - images/dummy/
    - images/svg/logo_head.svg
    - images/svg/logo_circle.svg
    - images/svg/logo_head_circle.svg
    - images/svg/logo_circle.png
    # - images/a_dot_ham.jpeg
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: font/OpenSans-Light.ttf
          weight: 300
        - asset: font/OpenSans-Regular.ttf
          weight: 400
        - asset: font/OpenSans-SemiBold.ttf
          weight: 600
        - asset: font/OpenSans-Bold.ttf
          weight: 700
        - asset: font/OpenSans-ExtraBold.ttf
          weight: 800
    - family: MavenPro
      fonts:
        - asset: font/Mavenpro-Regular.ttf
          weight: 400
        - asset: font/MavenPro-Medium.ttf
          weight: 500
        - asset: font/MavenPro-SemiBold.ttf
          weight: 600
        - asset: font/MavenPro-Bold.ttf
          weight: 700
        - asset: font/MavenPro-ExtraBold.ttf
          weight: 800
        - asset: font/MavenPro-Black.ttf
          weight: 900

    - family: Pinjam Icon
      fonts:
        - asset: font/PinjamIco.ttf
    - family: Kembali Icon
      fonts:
        - asset: font/KembaliIco.ttf
    - family: Widget Icon
      fonts:
        - asset: font/WidgetIcon.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
