/// Flutter icons WidgetIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WidgetIcon
///      fonts:
///       - asset: fonts/WidgetIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WidgetIcon {
  WidgetIcon._();

  static const _kFontFam = 'WidgetIcon';
  static const _kFontPkg = null;

  static const IconData kembali_ico = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinjam_ico = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
